services:
  - type: web
    name: biet-scholarship-management-system
    runtime: python
    buildCommand: ""
    startCommand: python akshara.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
