services:
  - type: web
    name: scholarship-management-system
    runtime: python
    buildCommand: ""
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
